---
language: python
services:
  - docker
env:
  global:
    - ROLE_NAME: hadoop_cli
  matrix:
    - MOLECULE_DISTRO: centos:6
      MOLECULE_JDK_VERSION: 7
    - MOLECULE_DISTRO: centos:7
      MOLECULE_JDK_VERSION: 8
    - MOLECULE_DISTRO: ubuntu:artful
      MOLECULE_JDK_VERSION: 8
    - MOLECULE_DISTRO: ubuntu:bionic
      MOLECULE_JDK_VERSION: 8
    - MOLECULE_DISTRO: ubuntu:cosmic
      MOLECULE_JDK_VERSION: 11
    - MOLECULE_DISTRO: ubuntu:trusty
      MOLECULE_JDK_VERSION: 7
    - MOLECULE_DISTRO: ubuntu:xenial
      MOLECULE_JDK_VERSION: 8
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker
before_script:
  - cd ../
  - mv ansible-role-${ROLE_NAME//_/-} rgibert.$ROLE_NAME
  - cd rgibert.$ROLE_NAME
script:
  - molecule test
